# Generated by Django 5.0.4 on 2024-06-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0003_menu1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(upload_to='icons/')),
            ],
        ),
        migrations.DeleteModel(
            name='Menu1',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
