# Generated by Django 5.0.4 on 2024-06-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0006_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='features/'),
        ),
    ]
