# Generated by Django 5.0.4 on 2024-06-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0007_alter_feature_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='FeatureImage/')),
            ],
        ),
    ]
