# Generated by Django 5.0.4 on 2024-06-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0009_containerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ItemProduct/')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.TextField()),
            ],
        ),
    ]
