# Generated by Django 5.0.4 on 2024-06-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0012_testimonial_delete_itemtestimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='company',
        ),
    ]
