# Generated by Django 5.0.4 on 2024-06-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0020_postblog_delete_aboutimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('phn', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='postblog',
            name='image',
            field=models.ImageField(upload_to='post_blogs/'),
        ),
    ]
