# Generated by Django 5.0.4 on 2024-06-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0023_product1_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
