# Generated by Django 5.0.4 on 2024-06-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0026_remove_product1_total_price_alter_product1_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=1000)),
            ],
        ),
    ]
