# Generated by Django 5.0.4 on 2024-06-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0027_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkout',
        ),
    ]
