# Generated by Django 5.0.4 on 2024-06-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0028_delete_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='featureicon',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='featureicon/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='persons/'),
        ),
        migrations.AlterField(
            model_name='postblog',
            name='image',
            field=models.ImageField(upload_to='post blogs/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.ImageField(upload_to='product2/'),
        ),
    ]
