# Generated by Django 5.0.4 on 2024-06-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0029_alter_about_image_alter_featureicon_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
