# Generated by Django 5.0.4 on 2024-06-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureapp', '0031_image_delete_totalcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
